name: TMT2 Release

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get tag name
        uses: olegtarasov/get-tag@v2.1
        id: tagName
        with:
          tagRegex: "(?<major>.*)\\.(?<minor>.*)"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          platforms: linux/amd64
          push: true
          build-args: |
            COMMIT_SHA=${{ github.sha }}
          tags: |
            xe1os/tmt2:${{ steps.tagName.outputs.major }}
            xe1os/tmt2:${{ steps.tagName.outputs.major }}.${{ steps.tagName.outputs.minor }}
